[package]
name = "calcula2r"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.9.6", features = ["v4_10"] }
evalexpr = "12.0"
regex = "1.11.1"
libadwaita = "0.7.2"
gtk4-sys = "0.9.6"
